<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "datamints_locallang_builder"
 *
 * Auto generated by Extension Builder 2021-11-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'datamints Locallang Builder',
    'description' => 'Offers developers and editors a backend module for creating, changing and translating language files for your extensions. Significant improvement of the workflow by using an independent translation provider such as Azure, DeepL or Google Translate.',
    'category' => 'module',
    'author' => 'Mark Weisgerber',
    'author_email' => 'mark.weisgerber@outlook.de / m.weisgerber@datamints.com',
    'state' => 'stable',
    'clearCacheOnLoad' => 1,
    'version' => '1.1.1',
    'constraints' => [
        'depends' => [
            'typo3' => '9.0.0-11.99.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
