services:
  _defaults:
    autowire: true
    autoconfigure: true

  Datamints\DatamintsLocallangBuilder\:
    resource: '../Classes/*'

  cache.cache:
    class: TYPO3\CMS\Core\Cache\Backend\BackendInterface
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'datamintslocallangbuilder_cache' ]
